learning_rate=0.0003 
n_steps=2048 
batch_size=64 
n_epochs=10 
gamma=0.99
gae_lambda=0.95 
clip_range=0.2
clip_range_vf=None
normalize_advantage=True
ent_coef=0.3 
vf_coef=0.5
max_grad_norm=0.5
use_sde=False
sde_sample_freq=-1
rollout_buffer_class=None 
rollout_buffer_kwargs=None
target_kl=None
stats_window_size=100
tensorboard_log=None 
policy_kwargs=None
verbose=0 
seed=None
device='auto'
_init_setup_model=True

# Environment Config
rewards = "dense"
total_timesteps = int(1e6)
episode_length = 500
n_episodes = total_timesteps/episode_length
eval_freq = 500